/* Static DTrace-compatible probes interface. */

#ifndef __LONGEARS_DTRACE_H__
#define __LONGEARS_DTRACE_H__

#include <amqp.h>

#ifdef HAVE_DTRACE

/* Autogenerated when configured --with-dtrace. */
#include "dtrace_probes.h"

#else /* No-op definitions. */

#ifdef __cplusplus
extern "C" {
#endif

inline void LONGEARS_CONSUMER_DECLARE(amqp_bytes_t *tag, int no_ack) {}
inline void LONGEARS_CONSUMER_CLOSE(amqp_bytes_t *tag, int by_server) {}
inline void LONGEARS_CONSUMER_QUEUE_CALLBACK(amqp_envelope_t *env) {}
inline void LONGEARS_CONSUMER_EVAL_CALLBACK(amqp_envelope_t *env) {}

#ifdef __cplusplus
}
#endif

#endif // HAVE_DTRACE

#endif // __LONGEARS_DTRACE_H__
