// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "longears_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// amqp_connect_
Rcpp::XPtr<AmqpConnection> amqp_connect_(std::string host, int port, std::string vhost, std::string username, std::string password, long timeout);
RcppExport SEXP _longears_amqp_connect_(SEXP hostSEXP, SEXP portSEXP, SEXP vhostSEXP, SEXP usernameSEXP, SEXP passwordSEXP, SEXP timeoutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type host(hostSEXP);
    Rcpp::traits::input_parameter< int >::type port(portSEXP);
    Rcpp::traits::input_parameter< std::string >::type vhost(vhostSEXP);
    Rcpp::traits::input_parameter< std::string >::type username(usernameSEXP);
    Rcpp::traits::input_parameter< std::string >::type password(passwordSEXP);
    Rcpp::traits::input_parameter< long >::type timeout(timeoutSEXP);
    rcpp_result_gen = Rcpp::wrap(amqp_connect_(host, port, vhost, username, password, timeout));
    return rcpp_result_gen;
END_RCPP
}
// amqp_disconnect_
void amqp_disconnect_(Rcpp::XPtr<AmqpConnection> conn);
RcppExport SEXP _longears_amqp_disconnect_(SEXP connSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<AmqpConnection> >::type conn(connSEXP);
    amqp_disconnect_(conn);
    return R_NilValue;
END_RCPP
}
// amqp_declare_queue_
void amqp_declare_queue_(Rcpp::XPtr<AmqpConnection> conn, std::string queue, bool quietly);
RcppExport SEXP _longears_amqp_declare_queue_(SEXP connSEXP, SEXP queueSEXP, SEXP quietlySEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<AmqpConnection> >::type conn(connSEXP);
    Rcpp::traits::input_parameter< std::string >::type queue(queueSEXP);
    Rcpp::traits::input_parameter< bool >::type quietly(quietlySEXP);
    amqp_declare_queue_(conn, queue, quietly);
    return R_NilValue;
END_RCPP
}
// amqp_publish_
void amqp_publish_(Rcpp::XPtr<AmqpConnection> conn, std::string queue, std::string msg, std::string content_type);
RcppExport SEXP _longears_amqp_publish_(SEXP connSEXP, SEXP queueSEXP, SEXP msgSEXP, SEXP content_typeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<AmqpConnection> >::type conn(connSEXP);
    Rcpp::traits::input_parameter< std::string >::type queue(queueSEXP);
    Rcpp::traits::input_parameter< std::string >::type msg(msgSEXP);
    Rcpp::traits::input_parameter< std::string >::type content_type(content_typeSEXP);
    amqp_publish_(conn, queue, msg, content_type);
    return R_NilValue;
END_RCPP
}
// amqp_get_
Rcpp::StringVector amqp_get_(Rcpp::XPtr<AmqpConnection> conn, std::string queue);
RcppExport SEXP _longears_amqp_get_(SEXP connSEXP, SEXP queueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<AmqpConnection> >::type conn(connSEXP);
    Rcpp::traits::input_parameter< std::string >::type queue(queueSEXP);
    rcpp_result_gen = Rcpp::wrap(amqp_get_(conn, queue));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_longears_amqp_connect_", (DL_FUNC) &_longears_amqp_connect_, 6},
    {"_longears_amqp_disconnect_", (DL_FUNC) &_longears_amqp_disconnect_, 1},
    {"_longears_amqp_declare_queue_", (DL_FUNC) &_longears_amqp_declare_queue_, 3},
    {"_longears_amqp_publish_", (DL_FUNC) &_longears_amqp_publish_, 4},
    {"_longears_amqp_get_", (DL_FUNC) &_longears_amqp_get_, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_longears(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
