# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

amqp_connect_ <- function(host = "localhost", port = 5672L) {
    .Call(`_longears_amqp_connect_`, host, port)
}

amqp_declare_queue_ <- function(conn, queue, quietly = FALSE) {
    invisible(.Call(`_longears_amqp_declare_queue_`, conn, queue, quietly))
}

amqp_publish_ <- function(conn, queue, msg, content_type = "text/plain") {
    invisible(.Call(`_longears_amqp_publish_`, conn, queue, msg, content_type))
}

amqp_get_ <- function(conn, queue) {
    .Call(`_longears_amqp_get_`, conn, queue)
}

