# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

amqp_connect_ <- function(host = "localhost", port = 5672L, vhost = "/", username = "guest", password = "guest", timeout = 10L) {
    .Call(`_longears_amqp_connect_`, host, port, vhost, username, password, timeout)
}

amqp_disconnect_ <- function(conn) {
    invisible(.Call(`_longears_amqp_disconnect_`, conn))
}

is_connected <- function(conn) {
    .Call(`_longears_is_connected`, conn)
}

amqp_declare_exchange_ <- function(conn, exchange, type, passive = FALSE, durable = FALSE, auto_delete = FALSE, internal = FALSE) {
    invisible(.Call(`_longears_amqp_declare_exchange_`, conn, exchange, type, passive, durable, auto_delete, internal))
}

amqp_delete_exchange_ <- function(conn, exchange, if_unused = FALSE) {
    invisible(.Call(`_longears_amqp_delete_exchange_`, conn, exchange, if_unused))
}

amqp_declare_queue_ <- function(conn, queue, passive = FALSE, durable = FALSE, exclusive = FALSE, auto_delete = FALSE) {
    .Call(`_longears_amqp_declare_queue_`, conn, queue, passive, durable, exclusive, auto_delete)
}

amqp_delete_queue_ <- function(conn, queue, if_unused = FALSE, if_empty = FALSE) {
    .Call(`_longears_amqp_delete_queue_`, conn, queue, if_unused, if_empty)
}

amqp_bind_queue_ <- function(conn, queue, exchange, routing_key = "") {
    invisible(.Call(`_longears_amqp_bind_queue_`, conn, queue, exchange, routing_key))
}

amqp_unbind_queue_ <- function(conn, queue, exchange, routing_key = "") {
    invisible(.Call(`_longears_amqp_unbind_queue_`, conn, queue, exchange, routing_key))
}

amqp_publish_ <- function(conn, routing_key, body, exchange = "", content_type = "text/plain", mandatory = FALSE, immediate = FALSE) {
    invisible(.Call(`_longears_amqp_publish_`, conn, routing_key, body, exchange, content_type, mandatory, immediate))
}

amqp_get_ <- function(conn, queue) {
    .Call(`_longears_amqp_get_`, conn, queue)
}

