# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

amqp_connect_ <- function(host = "localhost", port = 5672L, vhost = "/", username = "guest", password = "guest", timeout = 10L) {
    .Call(`_longears_amqp_connect_`, host, port, vhost, username, password, timeout)
}

amqp_disconnect_ <- function(conn) {
    invisible(.Call(`_longears_amqp_disconnect_`, conn))
}

is_connected <- function(conn) {
    .Call(`_longears_is_connected`, conn)
}

amqp_declare_queue_ <- function(conn, queue, quietly = FALSE) {
    invisible(.Call(`_longears_amqp_declare_queue_`, conn, queue, quietly))
}

amqp_publish_ <- function(conn, routing_key, body, exchange = "", content_type = "text/plain", mandatory = FALSE, immediate = FALSE) {
    invisible(.Call(`_longears_amqp_publish_`, conn, routing_key, body, exchange, content_type, mandatory, immediate))
}

amqp_get_ <- function(conn, queue) {
    .Call(`_longears_amqp_get_`, conn, queue)
}

